services:

  postgresql:
    image: docker.io/postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
     - postgresql:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: lmagomes@pm.me
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on: postgresql
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgresql:
  pgadmin-data: