version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - config:/config
      - cache:/cache
      - /mnt/disk/media:/media:Z
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://media

volumes:
  config:
  cache: