version: "3.9"
services:

  minecraft:
    build:
      context: papermc
    volumes:
      - server-data:/server
    # ports:
    #   - 25565:25565

  velocity:
    build:
      context: velocity
    volumes:
      - proxy-data:/server
    ports:
      - 25577:25577

  overviewer:
    image: mide/minecraft-overviewer:latest
    environment:
      MINECRAFT_VERSION: "1.19"
    volumes:
      - server-data:/home/minecraft/server/:ro
      - overviwer-data:/home/minecraft/render/

  nginx:
    image: nginx
    volumes:
     - overviwer-data:/usr/share/nginx/html
    environment:
    - NGINX_HOST=overviewer


volumes:
  server-data:
  proxy-data:
  overviwer-data:

networks:
  default:
    external:
      name: proxy