version: '3.4'
services:
  miniflux:
    image: miniflux/miniflux:latest
    # ports:
    #   - "80:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:miniflux@mila/miniflux?sslmode=disable
      - BASE_URL=https://miniflux/

networks:
  default:
    external:
      name: proxy
      
# podman run -d \
#   -p 80:8080 \
#   --name miniflux \
#   -e "DATABASE_URL=postgres://miniflux:miniflux@mila/miniflux?sslmode=disable" \
#   -e "RUN_MIGRATIONS=1" \
#   -e "CREATE_ADMIN=1" \
#   -e "ADMIN_USERNAME=miniflux" \
#   -e "ADMIN_PASSWORD=miniflux" \
#   miniflux/miniflux:latest
