---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #optional
      # - USER=username #optional
      # - PASS=password #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=peerport #optional
      - HOST_WHITELIST=torrents
    volumes:
      - config:/config
      - /mnt/disk/downloads:/downloads:Z
      - watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  config:
  watch:

networks:
  default:
    external:
      name: proxy