version: '3'
services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy-data:/data
      - proxy-letsencrypt:/etc/letsencrypt


volumes:
  proxy-data:
    driver: local
  proxy-letsencrypt:
    driver: local

networks:
  default:
    external:
      name: proxy
